### ISSUE TITLE
Remove generic element selectors

### ISSUE THREAD

**Issue by shaunbent** [beckytrav/build-page#6]
Throughout your styles you've used lots and lots of '[element selectors](http://www.w3schools.com/cssref/sel_element.asp)'. An "element selector" is where you're applying rules directly to an element, for example:

``` css
header {
    background-color: #ffdf43;
    width: 100%;
    position: relative;
    padding-top: 12px;
    padding-left: 10px;
    padding-bottom: 0px;
    margin-bottom: 0px;
    text-transform: uppercase;
    outline-style: none;
}
```

Here your targeting every `<header>` element on the page, giving it some specific `padding`, forcing all the text to be uppercase and giving it a nice yellow `background-color`. 

For this little prototype its ok and it works but what if we added another new component that also used the `<header>` element but was styled differently. This would break.

Give this section a read about "Dangerous Selector" as it explains what I'm talking about: http://csswizardry.com/2012/11/code-smells-in-css/#dangerous-selectors

Not all element selectors are bad, they can be useful. If you've got a rule that you know is always going to be true then you can use them. Something like:

``` css
h1 {
    font-size: 40px;
    font-family: 'Gill Sans MT', 'Gill Sans', Calibri, sans-serif;
}
```

If you know that all `<h1>` element will have `font-size: 40px;` and `font-family: 'Gill Sans MT', 'Gill Sans', Calibri, sans-serif;` its ok to say that, it saves you from repeating this over and over.

If you need to do something specific like for the "site header" it needs some padding, then create a class and apply the padding to that. So you'd end up with something like:

**HTML**

``` html
<h1 class="site-title">Sport</h1>
```

**CSS**

``` css
h1 {
    font-size: 40px;
    font-family: 'Gill Sans MT', 'Gill Sans', Calibri, sans-serif;
}

.site-title {
    padding-left: 15px;
    padding-bottom: 10px;
    color: #000;
    text-transform: uppercase;
}
```

Now we can use lots of `<h1>`s on the page but only a `<h1>` with a class of `site-title` will get the site-title styling.

**HIGH FIVE!!**

![High Five](http://media.giphy.com/media/C4lSxWjqSJLfG/giphy.gif)

Think about this approach of where you should and shouldn't use "element selectors" and give your code a bit of a refactor to try and remove as many of them as you can. Adding lots of classes is a good thing. It helps you keep your code maintainable and scalable so you can add new components without having to unset load of generic style rules you've created at the start.
